### ISSUE TITLE
/api/chat returns correct data but nothing is rendered on interface

### ISSUE THREAD

**Issue by cheraff** [letrieu/cloudflare-chatbot#1]
Great work, so much so I wanted to give this a role myself - ran into some issues.

1. When I followed the instructions in README the build process on cloudflare application creation returns a wrangler file error, suggesting something about a build directory missing, when added, it gets ignored and continues to fail.

3. When I install manually everything gets setup correctly and the /api/chat endpoint correctly returns replies to questions, however they are not actually rendered on the interface like in your demo

A few of your packages were outdated, I tried with new versions, and again with your versions. Same issues.

No idea what's causing this.  

Video for your reference: https://youtu.be/R5axUE_lgUs

**Comment by letrieu** [comment]
It is a breaking change for `StreamingTextResponse` from [vercel/ai](https://github.com/vercel/ai) version 3.0.20
Same issue in: [#1306 3.0.20 create a breaking change for StreamingTextResponse](https://github.com/vercel/ai/issues/1316)
I fixed this issue in commit: 925241c7f59a1e6c645df706b868a4e440a68147
